[pre-commit]
parallel = true

[pre-commit.commands.format]
run = "pnpm fix"
glob = "*.{ts,tsx,css,json}"
stage_fixed = true

[pre-commit.commands.typecheck]
run = "pnpm typecheck"
glob = "*.{ts,tsx}"
