name: deploy

on:
  workflow_run:
    workflows: ["checks"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Get repository name
        run: |
          REPOSITORY_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)
          echo "REPOSITORY_NAME=$REPOSITORY_NAME" >> $GITHUB_ENV
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=${{ env.REPOSITORY_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
